# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f94dfa9f877da2ceeda40e1b48d2af2aea4a6a0366724c5d162e5ec0b9f49c855ef9cf3b3c51b6fbc567d2418550c7d6de726de2e344c7a320c6b5c6b23c14d6

test:
  secret_key_base: ffe13248603fe3e49b83c7b2bf0de86f38f4e48070c6a7031f3c2099e95e30ee9a22d14572754c08237b18de43aaf658e32386c8b209705c690bba96d77db09d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
